### ISSUE TITLE
tagged unions are modeled wrong in the AST

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/pydsdl#32]
Unions in the AST are modeled as if they were structs which confounds symmetrical parsing logic since each field is treated as a data member instead of an alternate representation of a single data member. Tagged unions should become structure types containing a single field that is an anonymous-union compound type. This compound type's fields would be the alternate representation of that field.

## Proposed

![image](https://user-images.githubusercontent.com/19180861/73476606-6eddf380-4347-11ea-8217-9154cd8706d8.png)

**Comment by pavel-kirienko** [comment]
I agree in general but:

- Shouldn't the `TaggedUnionType` inherit from `CompositeType` directly? It is not a concretization of the structure type.
- Are you sure "anonymous" is a good choice of word here? May I suggest "untagged"?

**Comment by thirtytwobits** [comment]
> * Shouldn't the `TaggedUnionType` inherit from `CompositeType` directly? It is not a concretization of the structure type.

okaaaaaaaaaay.

> * Are you sure "anonymous" is a good choice of word here? May I suggest "untagged"?

sure

![image](https://user-images.githubusercontent.com/19180861/73479287-93889a00-434c-11ea-9925-aa285549d004.png)

**Comment by thirtytwobits** [comment]
Actually no, should the UntaggedUnionType be simply a Serializable?

![image](https://user-images.githubusercontent.com/19180861/73479426-d0ed2780-434c-11ea-9400-c2dee19900c1.png)

**Comment by pavel-kirienko** [comment]
> Actually no, should the UntaggedUnionType be simply a Serializable?

But it is composed of multiple attributes, so it is a Composite? Also, its sibling Tagged Union should be a composite anyway; given that, making the Untagged one different makes the design somewhat non-obvious?

**Comment by thirtytwobits** [comment]
My point is the TaggedUnionType contains a set of fields that must be serialized and deserialized whereas the UntaggedUnionType contains a set of fields only one of which will be serialized and deserialized. This means that, for the purposes of serialization, the untagged union acts as one-type-at-a-time which suggests it is not a composite?

**Comment by pavel-kirienko** [comment]
Untagged unions are not special enough to warrant a new node directly under Serializable in the [data type model](https://github.com/UAVCAN/pydsdl#data-type-model). Let's say that "one-type-at-a-time" is just a special mode of composition.

**Comment by thirtytwobits** [comment]
Well, if you don't agree that a TaggedUnion is a structure with a single tag field and a single union field then this whole issue is moot. To me a tagged union is:

```
struct MyTaggedUnion
{
    unsigned tag;
    union
    {
        type0 field0;
        type1 field1;
    } my_union;
};
```
such that my_union is another type of Attribute rather than being a composite.

**Comment by pavel-kirienko** [comment]
Okay, let's try it this way.

**Comment by thirtytwobits** [comment]
Pleasure doing business with you.
