### ISSUE TITLE
Mysterious error for mundane misuse

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/pydsdl#46]
https://github.com/UAVCAN/pydsdl/blame/53ff51712e2cc7e407e130aa9639ce46194664a0/pydsdl/_namespace.py#L165 will cause a list index out of range if the target folder contains no DSDL files. An error should say something to this effect instead of crashing on a random logging statement.

**Comment by pavel-kirienko** [comment]
Already fixed in https://github.com/UAVCAN/pydsdl/commit/abb5f0fdde88c9acf96d3066ad93f5ad0c889b24, duplicates #41.
